#!/bin/bash
#
# Excellent Regards, the Alveare Solutions #!/Society -x
#
# (A)Risk init wrapper

DOES_ANYBODY_WATCH_TV_ANYMORE='no'
TV_INIT_WRAPPER='./tv-init'
FC_INIT_WRAPPER='./fc-setup'
AR_INIT='./asymetric_risk.py'
AR_DIR=`dirname ${AR_INIT}`

cd ${AR_DIR} &> /dev/null
if [ $? -ne 0 ]; then
    echo "[ ERROR ]: Directory not found! (${AR_DIR})"
    return 1
fi

for opt in $@; do
    case "${opt}" in
        '--television')
            DOES_ANYBODY_WATCH_TV_ANYMORE='yes'
            ;;
        '--setup')
            ${FC_INIT_WRAPPER}
            exit $?
            ;;
    esac
done

if [[ ${DOES_ANYBODY_WATCH_TV_ANYMORE} == 'yes' ]]; then
    ${TV_INIT_WRAPPER}
fi

${AR_INIT} $@ 2> /dev/null
EXIT_CODE=$?

if [[ "$1" == '-h' ]] || [[ "$1" == '--help' ]]; then
    cat<<EOF
  --setup               Ensure project file structure consistency, installs
                        Python3 dependencies and updates system date/time in
                        order to ensure that the Binance API keys work properly.

EOF
fi

cd - &> /dev/null

exit $EXIT_CODE
