#!/bin/bash
#
# Excellent Regards, the Alveare Solutions #!/Society -x
#
# FlowCTRL Setup Procedure

PROCEDURE_SKETCH="dta/fc_setup_procedure.json"

./src/FlowCTRL/flow-init --start --sketch-file=${PROCEDURE_SKETCH}

exit $?
