#!/bin/bash
#
# Excellent Regards, the Alveare Solutions #!/Society -x
#
# TeleVision bot-ctrl init process

CURRENT_DIR="$(
    cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd
)"
TV_INIT="${CURRENT_DIR}/src/TeleVision/television.py"
LOG_FILE="${CURRENT_DIR}/log/asymetric_risk.log"
CONF_FILE="${CURRENT_DIR}/conf/television.conf.json"
PID_FILE="${CURRENT_DIR}/.tv-bot.pid"
ACTION='bot-ctrl'
CMD="${TV_INIT} --log-file=${LOG_FILE} --config-file=${CONF_FILE} --action=${ACTION} --watchdog &> /dev/null &"

${CMD} &> /dev/null &
echo $! > ${PID_FILE}; cat ${PID_FILE}
exit $?
